### ISSUE TITLE
성폭력 예방교육 - 미투운동 그 후 (학생용) (8분 7초)에서

### ISSUE THREAD

**Issue by youngToMaturity** [rmfpdlxmtidl/Auto-sexual-violence-prevention-education#1]
VM65:7 Uncaught TypeError: Cannot read property 'val' of null
    at <anonymous>:7:18

라는 오류가 발생합니다

**Comment by youngToMaturity** [comment]
새로 고침하니 되는군요! '#vid'를 불러오는데에 문제가 발생하지 않았나 싶습니다 감사합니다

**Comment by gwak2837** [comment]
가끔 네트워크 연결 문제로 그런 오류가 뜨긴 해요. 새로고침 하면 될 거에요:)

**Comment by youngToMaturity** [comment]
네 확인했습니다 좋은 기능 감사합니다

2020년 6월 30일 (화) 오후 3:42, 곽태욱 <notifications@github.com>님이 작성:
